#
# Copyright (c) 2013-2014 by Lifted Studios. All Rights Reserved.
#

Style/LineLength:
  Enabled: true
  Max: 100

Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false
