#!/bin/sh

alias tlf="tail -f"
alias ln='ln -v'
alias mkdir='mkdir -p'
alias ...='../..'
alias -g G='| grep'
alias -g M='| less'
alias -g L='| wc -l'

alias migrate="rake db:migrate db:rollback && rake db:migrate"
alias m="migrate"
alias rk="rake"
alias s="rspec"

alias df='df -h -T hfs'
alias du='du -h'

alias f='find . -name'

alias l='ls -F'
alias ll='ls -lhF'
alias la='ls -lhaF'

alias sssh='screen-ssh'

alias a='atom'
alias aa='atom-alpha'
alias ab='atom-beta'

alias pv='package-version'

alias flushdns="sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder; echo 'Flushed DNS, btw here is your hosts file just in case:'; cat /etc/hosts"
