#!/bin/zsh
alias tlf="tail -f"
alias ln='ln -v'
alias mkdir='mkdir -p'
alias ...='../..'
alias -g G='| grep'
alias -g M='| less'
alias -g L='| wc -l'

# Rails
alias migrate="rake db:migrate db:rollback && rake db:migrate"
alias m="migrate"
alias rk="rake"
alias s="rspec"

alias df='df -h'
alias du='du -h'

alias f='find . -name'

alias l='ls -F'
alias ll='ls -lhF'
alias la='ls -lhaF'
