#!/bin/sh

alias tlf="tail -f"
alias ln='ln -v'
alias mkdir='mkdir -p'
alias ...='../..'
alias -g G='| grep'
alias -g M='| less'
alias -g L='| wc -l'

alias df='df -h -T hfs'
alias du='du -h'

alias f='find . -name'

alias l='ls -F'
alias ll='ls -lhF'
alias la='ls -lhaF'

alias sssh='screen-ssh'

alias a='atom'
alias ab='atom-beta'

alias pv='package-version'

alias flushdns="sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder; echo 'Flushed DNS, btw here is your hosts file just in case:'; cat /etc/hosts"

# Un-wedge the built-in camera
alias kill-camera="sudo killall VDCAssistant"

alias ex="exercism"
