source 'https://rubygems.org'

gem 'aws-sdk'
gem 'highline'
gem 'octokit'
gem 'parity'
gem 'plist'
gem 'powerpack'
gem 'pry'
gem 'rest-client'
gem 'rubocop'
gem 'ruby-progressbar'
gem 'scss_lint'
gem 'trollop', '~> 2.0'
